runtime: python
env: flex
service: urbandata-poc-cron
api_version: 1
threadsafe: true

handlers:
- url: /job_business
  script: job_business.app

- url: /job_review
  script: job_review.app

- url: /job_analysis
  script: job_analysis.app